### ISSUE TITLE
Would like to discuss.

### ISSUE THREAD

**Issue by Noemata** [rneeft/Caliburn.Micro.Universal#1]
Is there some way we could discuss your developments more directly through email or other means?  I have some ideas for your framework enhancements.

Thanks.

**Comment by rneeft** [comment]
Hi Mario,

Thank you for your email. I’m always open to framework enhancements.

I’m currently on holiday until 7 January. I’ll contact you then.

Rick

**Comment by rneeft** [comment]
Hi @Noemata ,

What kind of idea's do you have?

Rick
